2022-03-14 12:01:52,877 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-14 12:01:52,877 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\Bajwa\AppData\Local\Programs\Python\Python39\lib\site-packages\instabot\bot\bot.py
2022-03-14 12:01:52,878 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-14 12:01:53,072 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-14 12:01:53,240 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-14 12:01:53,397 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-14 12:01:53,563 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-03-14 12:01:56,873 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-03-14 12:01:56,874 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXF0vJ8vGLCkDaFk6XV4fOX8WDqvRAFXPqeGQTHVAWUB_PKzzYZpnt14K58dRsnaxyM2Jxw/bievzANJdO/","api_path":"/challenge/AXF0vJ8vGLCkDaFk6XV4fOX8WDqvRAFXPqeGQTHVAWUB_PKzzYZpnt14K58dRsnaxyM2Jxw/bievzANJdO/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-03-14 12:01:56,874 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-14 12:01:56,874 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-03-14 12:01:56,874 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-03-14 12:01:59,691 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-03-14 12:01:59,691 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'yoda.jpg' is not uploaded.
